#############################################################################
# Makefile for building: dist/RunActiveContoursQt
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Feb 16 11:53:58 2015
# Project:  Project.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -w -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I../OZlib -I../../OzOpenCL -I/usr/local/cuda-5.5/include -I../SignedDistanceFunction/src/headers -I/usr/include/GL -I/usr/include/nifti -Isrc/headers -Isrc/forms/headers -I/usr/X11R6/include -Ibuild/moc -Isrc/forms/headers
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -L/home/olmozavala/Dropbox/OzOpenCL/OZlib -lGLU -lglut -lGLEW -lX11 -lm -lFileManager -lOpenCL -lGLManager -lCLManager -lImageManager -lGordonTimers -lfreeimage -lniftiio -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/ActiveContours.cpp \
		src/CameraMovement.cpp \
		src/FPSMovement.cpp \
		src/GLWidget.cpp \
		src/main.cpp \
		src/Tools.cpp \
		src/forms/src/MainWindowOZ.cpp \
		../SignedDistanceFunction/src/SignedDistFunc.cpp build/moc/moc_GLWidget.cpp \
		build/moc/moc_MainWindowOZ.cpp
OBJECTS       = build/ActiveContours.o \
		build/CameraMovement.o \
		build/FPSMovement.o \
		build/GLWidget.o \
		build/main.o \
		build/Tools.o \
		build/MainWindowOZ.o \
		build/SignedDistFunc.o \
		build/moc_GLWidget.o \
		build/moc_MainWindowOZ.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Project.pro
QMAKE_TARGET  = RunActiveContoursQt
DESTDIR       = dist/
TARGET        = dist/RunActiveContoursQt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/forms/headers/ui_MainWindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) dist/ || $(MKDIR) dist/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Project.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Project.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Project.pro

dist: 
	@$(CHK_DIR_EXISTS) build/RunActiveContoursQt1.0.0 || $(MKDIR) build/RunActiveContoursQt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/RunActiveContoursQt1.0.0/ && $(COPY_FILE) --parents src/headers/ActiveContours.h src/headers/CameraMovement.h src/headers/FPSMovement.h src/forms/headers/GLWidget.h src/forms/headers/MainWindowOZ.h ../SignedDistanceFunction/src/headers/SignedDistFunc.h build/RunActiveContoursQt1.0.0/ && $(COPY_FILE) --parents src/ActiveContours.cpp src/CameraMovement.cpp src/FPSMovement.cpp src/GLWidget.cpp src/main.cpp src/Tools.cpp src/forms/src/MainWindowOZ.cpp ../SignedDistanceFunction/src/SignedDistFunc.cpp build/RunActiveContoursQt1.0.0/ && $(COPY_FILE) --parents src/forms/ui/MainWindow.ui build/RunActiveContoursQt1.0.0/ && (cd `dirname build/RunActiveContoursQt1.0.0` && $(TAR) RunActiveContoursQt1.0.0.tar RunActiveContoursQt1.0.0 && $(COMPRESS) RunActiveContoursQt1.0.0.tar) && $(MOVE) `dirname build/RunActiveContoursQt1.0.0`/RunActiveContoursQt1.0.0.tar.gz . && $(DEL_FILE) -r build/RunActiveContoursQt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc/moc_GLWidget.cpp build/moc/moc_MainWindowOZ.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_GLWidget.cpp build/moc/moc_MainWindowOZ.cpp
build/moc/moc_GLWidget.cpp: src/forms/headers/GLWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/forms/headers/GLWidget.h -o build/moc/moc_GLWidget.cpp

build/moc/moc_MainWindowOZ.cpp: src/forms/headers/GLWidget.h \
		src/forms/headers/ui_MainWindow.h \
		src/forms/headers/MainWindowOZ.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/forms/headers/MainWindowOZ.h -o build/moc/moc_MainWindowOZ.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/forms/headers/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) src/forms/headers/ui_MainWindow.h
src/forms/headers/ui_MainWindow.h: src/forms/ui/MainWindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/forms/ui/MainWindow.ui -o src/forms/headers/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/ActiveContours.o: src/ActiveContours.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ActiveContours.o src/ActiveContours.cpp

build/CameraMovement.o: src/CameraMovement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/CameraMovement.o src/CameraMovement.cpp

build/FPSMovement.o: src/FPSMovement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/FPSMovement.o src/FPSMovement.cpp

build/GLWidget.o: src/GLWidget.cpp src/Tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GLWidget.o src/GLWidget.cpp

build/main.o: src/main.cpp src/forms/headers/ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/Tools.o: src/Tools.cpp src/Tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Tools.o src/Tools.cpp

build/MainWindowOZ.o: src/forms/src/MainWindowOZ.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MainWindowOZ.o src/forms/src/MainWindowOZ.cpp

build/SignedDistFunc.o: ../SignedDistanceFunction/src/SignedDistFunc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SignedDistFunc.o ../SignedDistanceFunction/src/SignedDistFunc.cpp

build/moc_GLWidget.o: build/moc/moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_GLWidget.o build/moc/moc_GLWidget.cpp

build/moc_MainWindowOZ.o: build/moc/moc_MainWindowOZ.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MainWindowOZ.o build/moc/moc_MainWindowOZ.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

